"""create initial tables

Revision ID: d7ff0c271224
Revises: 
Create Date: 2026-05-27 18:06:12.641673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ff0c271224'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('corretores',
    sa.Column('id_corretor', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('creci', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id_corretor'),
    sa.UniqueConstraint('creci')
    )
    op.create_table('proprietarios',
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.PrimaryKeyConstraint('id_proprietario'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('contratos',
    sa.Column('id_contrato', sa.Integer(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=20), nullable=False),
    sa.Column('valor_transacao', sa.Float(), nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('id_corretor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_corretor'], ['corretores.id_corretor'], ),
    sa.PrimaryKeyConstraint('id_contrato')
    )
    op.create_table('imoveis',
    sa.Column('id_imovel', sa.Integer(), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('tipo_imovel', sa.String(length=50), nullable=True),
    sa.Column('valor_base', sa.Float(), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proprietario'], ['proprietarios.id_proprietario'], ),
    sa.PrimaryKeyConstraint('id_imovel')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imoveis')
    op.drop_table('contratos')
    op.drop_table('proprietarios')
    op.drop_table('corretores')
    op.drop_table('clientes')
    # ### end Alembic commands ###
